server:
  port: 8080
spring:
  application:
    name: springcloud-config-svn
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri:  http://192.168.25.7/svn/repo/config-repo
          username:
          password:
          default-label: trunk
      profiles:
        active: subversion



